15/03/23
berlinblonde/pytest pull request #3
Opened 2023-07-18 17:03 UTC by berlinblonde

2023-07-19 10:37 UTC, alinashabalina reviewed
Вот про эту проблему git add . я и говорила: иногда в гит отправляется всякий хлам, типа вот этого pycache, поэтому пользоваться надо с осторожностью.
Мы с тобой, когда будем делать [рефакторинг кода](https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3), уберём эту папку, пока не критично

2023-07-19 10:40 UTC, alinashabalina reviewed
Прочитай ещё, пожалуйста, соглашение про наименование коммитов (git commit -m "Message") https://www.conventionalcommits.org/ru/v1.0.0-beta.2/

мы с тобой для скорости написали всякие там hophop и opop, но так лучше не делать)))

2023-07-19 11:06 UTC, alinashabalina requested changes

2023-07-19 11:06 UTC, alinashabalina commented on test/conftest.py
> +import pytest
Вот тут нужно поправить импорты (опять же, мы для скорости писали от балды, но в [PEP8](https://peps.python.org/pep-0008) есть правила, [по которым](https://peps.python.org/pep-0008/#imports) надо делать импорты. Если не хочешь держать это в голове, можно воспользоваться средствами PyCharm:
Code - Optimize imports

2023-07-19 11:06 UTC, alinashabalina commented on test/test_4.py
> +
Вот в этом файле и вообще по всем файлам у нас гуляют то ординарные, то двойные кавычки. По [документации](https://peps.python.org/pep-0008/#string-quotes) надо выбрать одни какие-нибудь и их придерживаться. Чтобы не делать это руками (God help us), можно воспользоваться помощью от PyCharm:

Edit - Find - Replace

2023-07-19 11:06 UTC, alinashabalina commented on test/test_4.py
> +
Также надо обратить внимание на пробелы, их не хватает. В [документации](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements) описано, на что обращать внимание

PyCharm:  Code - Reformat File

2023-07-19 11:06 UTC, alinashabalina commented on test/test_4.py
> +
Между функциями, не являющимися методами одного класса, пробел -  две линии

2023-07-19 11:06 UTC, alinashabalina commented on test/test_4.py
> +
И тут тоже должно быть две

2023-07-19 11:06 UTC, alinashabalina commented on test/test_4.py
> +
И тут и дальше по всем файлам

2023-07-27 12:36 UTC, berlinblonde commented on test/conftest.py
> +import pytest
+

2023-07-27 12:36 UTC, berlinblonde commented on test/test_4.py
> +
+

2023-07-27 12:36 UTC, berlinblonde commented on test/test_4.py
> +
+

2023-07-27 12:36 UTC, merged