tests
berlinblonde/pytest pull request #4
Opened 2023-07-25 07:02 UTC by berlinblonde

2023-07-26 17:19 UTC, alinashabalina requested changes

2023-07-26 17:19 UTC, alinashabalina commented on test/conftest.py
> +
Это тоже фикстура, обрати внимание на строчку 5 в этом файле, надо такое же добавить

2023-07-26 17:19 UTC, alinashabalina commented on test_7.py
> +def test_function20():
А вот в этой функции надо использовать как раз фикстуру из conftest.py, чтобы выдавалось опрелённое количество записей на странице и на определённом номере страницы. То есть:

эта функция будет принимать аргументом функцию из conftest.py, а здесь то, что та функция возвращает, должно использоваться в качестве **параметров** запроса

2023-07-26 17:19 UTC, alinashabalina commented on test/conftest.py
> +def create_dict():
Переназови, пожалуйста, функцию: сейчас название create_dict говорит нам о том, что создался словарь, а нам для постоянного переиспользования этой функции в других местах этого недостаточно. В данной функции мы создаём фильтрацию по страницам, можно отталкиваться от этого)


Вот тут статья по теме https://medium.com/swlh/how-to-better-name-your-functions-and-variables-e962a4ef335b

2023-07-26 17:19 UTC, alinashabalina commented on test_7.py
> +    print(result)
Ну тут либо возвращать, либо печатать)

Ты можешь печатать (в том числе и в тестах) для дебага, чтобы проверить, что ты всё ок сделала, но обычно в реальном проекте на ревью за такое ругаются) Давай убирать

2023-07-26 17:19 UTC, alinashabalina commented on test_7.py
> +    print('Negative:', negative)
И вот тут тоже

2023-07-26 17:19 UTC, alinashabalina commented on test_7.py
> +    print('Positive:', positive)
И тут

2023-07-26 17:19 UTC, alinashabalina commented on test_7.py
> +def test_function_22(x):
А почему тут функция принимает аргумент? Почитай, пожалуйста, [статью](https://sky.pro/media/funktsii-v-python/#:~:text=%D0%92%20Python%20%D0%B0%D1%80%D0%B3%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%20%D0%B1%D1%8B%D0%B2%D0%B0%D1%8E%D1%82,%D0%B0%D1%80%D0%B3%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2%20%D0%BC%D0%BE%D0%B3%D1%83%D1%82%20%D0%B1%D1%8B%D1%82%D1%8C%20%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9%20%D0%B4%D0%BB%D0%B8%D0%BD%D1%8B.) про типы аргументов в питоне, там прям примеры есть, если не успеешь разобраться - будем на занятии разбирать вместе)

2023-07-26 17:19 UTC, alinashabalina commented on test_7.py
> +    for i in x:
Кстати, а давай тут попробуем в одну строку записать цикл for? Это называется list comprehension и записывается [вот так](https://python-scripts.com/for-in-one-line)

2023-07-27 12:27 UTC, berlinblonde commented on test/conftest.py
> +
+

2023-07-27 12:28 UTC, berlinblonde commented on test_7.py
> +def test_function20():
+

2023-07-27 12:28 UTC, berlinblonde commented on test/conftest.py
> +def create_dict():
+

2023-07-27 12:28 UTC, alinashabalina approved these changes

2023-07-27 12:30 UTC, merged