exercises
berlinblonde/pytest pull request #5
Opened 2023-08-01 08:44 UTC by berlinblonde

2023-08-01 13:31 UTC, alinashabalina requested changes

2023-08-01 13:31 UTC, alinashabalina commented on test/test_8.py
> +    i = [1, 10]
В задании предлагали итерироваться по промежутку от 1 до 10, вот тут надо подумать)

2023-08-01 13:31 UTC, alinashabalina commented on test/test_8.py
> +        print(i)
Помни про печать, она для дебага

2023-08-01 13:31 UTC, alinashabalina commented on test/test_8.py
> +        a, b = b, a
Не очень поняла, зачем тут их местами менять. Пояснишь?

2023-08-05 06:43 UTC, berlinblonde commented on test/test_8.py
> +        a, b = b, a
> Не очень поняла, зачем тут их местами менять. Пояснишь?
шуршала по каким-то похожим задачам в стековерфлоу, увидела такое решение, смысловую нагрузку строки поняла, а почему оно так - не поняла)) поэтому решила оставить.

2023-08-05 06:43 UTC, berlinblonde commented on test/test_8.py
> +        print(i)
да, помню)

2023-08-05 06:43 UTC, berlinblonde commented on test/test_8.py
> +    i = [1, 10]
с нуля надо

2023-08-22 19:13 UTC, merged